-- ============================================================
-- Script type: rebuild
-- Version: R20260608
-- Scope: full
-- Description: Full rebuild SQL aligned to the exported live schema
--              under D:\develop\1\sql.
-- Notes:
--   1. This file keeps table DDL, comments, and indexes.
--   2. All exported data INSERT statements are removed except the
--      current three t_sample_question rows.
--   3. Run this file against an empty schema, or clear public schema
--      before execution.
-- ============================================================

create extension if not exists vector;

create table t_user
(
    user_id       bigint generated by default as identity
        primary key,
    username      varchar(64)                                      not null,
    password_hash varchar(255)                                     not null,
    phone         varchar(32),
    email         varchar(128),
    display_name  varchar(64),
    user_type     varchar(128) default 'USER'::character varying   not null,
    status        varchar(16)  default 'ACTIVE'::character varying not null,
    deleted       smallint     default 0                           not null,
    created_at    timestamp    default CURRENT_TIMESTAMP           not null,
    updated_at    timestamp    default CURRENT_TIMESTAMP           not null
);

alter table t_user
    owner to postgres;

create unique index uk_t_user_username_deleted
    on t_user (username, deleted);

create unique index uk_t_user_phone_deleted
    on t_user (phone, deleted);

create unique index uk_t_user_email_deleted
    on t_user (email, deleted);

create index idx_t_user_status_deleted
    on t_user (status, deleted);

create index idx_t_user_user_type_deleted
    on t_user (user_type, deleted);


create table t_verify_code_record
(
    record_id    bigint generated by default as identity
        primary key,
    biz_type     varchar(64)                                  not null,
    biz_id       varchar(64),
    subject_type varchar(32),
    subject_id   bigint,
    target_type  varchar(16)                                  not null,
    target_value varchar(128)                                 not null,
    channel      varchar(16) default 'SMS'::character varying not null,
    template_id  varchar(100),
    provider     varchar(64),
    request_id   varchar(128),
    code_value   varchar(64)                                  not null,
    expires_at   timestamp                                    not null,
    used         boolean     default false                    not null,
    used_at      timestamp,
    deleted      smallint    default 0                        not null,
    created_at   timestamp   default CURRENT_TIMESTAMP        not null,
    remark       varchar(500)
);

alter table t_verify_code_record
    owner to postgres;

create index idx_t_verify_code_record_lookup
    on t_verify_code_record (biz_type, target_type, target_value, code_value, used, deleted, expires_at);

create index idx_t_verify_code_record_subject
    on t_verify_code_record (subject_type, subject_id, deleted);

create index idx_t_verify_code_record_request_id
    on t_verify_code_record (request_id);


create table t_auth_session
(
    session_id     bigint generated by default as identity
        primary key,
    subject_id     bigint                              not null,
    subject_type   varchar(32)                         not null,
    login_type     varchar(32)                         not null,
    token_digest   varchar(64)                         not null,
    expires_at     timestamp                           not null,
    revoked        boolean   default false             not null,
    deleted        smallint  default 0                 not null,
    created_at     timestamp default CURRENT_TIMESTAMP not null,
    last_active_at timestamp default CURRENT_TIMESTAMP not null,
    device_type    varchar(32),
    client_ip      varchar(64)
);

alter table t_auth_session
    owner to postgres;

create unique index uk_t_auth_session_token_digest_deleted
    on t_auth_session (token_digest, deleted);

create index idx_t_auth_session_subject_deleted
    on t_auth_session (subject_id, subject_type, revoked, deleted);

create index idx_t_auth_session_expires_at
    on t_auth_session (expires_at);


create table t_ingestion_pipeline
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(100)                        not null,
    description text,
    created_by  bigint,
    updated_by  bigint,
    deleted     smallint  default 0                 not null,
    create_time timestamp default CURRENT_TIMESTAMP not null,
    update_time timestamp default CURRENT_TIMESTAMP not null,
    constraint uk_t_ingestion_pipeline_name_deleted
        unique (name, deleted)
);

comment on table t_ingestion_pipeline is '摄取流水线表';

comment on column t_ingestion_pipeline.id is '主键ID';

comment on column t_ingestion_pipeline.name is '流水线名称';

comment on column t_ingestion_pipeline.description is '流水线描述';

comment on column t_ingestion_pipeline.created_by is '创建人用户ID';

comment on column t_ingestion_pipeline.updated_by is '更新人用户ID';

comment on column t_ingestion_pipeline.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_ingestion_pipeline.create_time is '创建时间';

comment on column t_ingestion_pipeline.update_time is '更新时间';

alter table t_ingestion_pipeline
    owner to postgres;

create index idx_t_ingestion_pipeline_created_by
    on t_ingestion_pipeline (created_by);


create table t_ingestion_pipeline_node
(
    id             bigint generated by default as identity
        primary key,
    pipeline_id    bigint                                not null,
    node_id        varchar(64)                           not null,
    node_type      varchar(30)                           not null,
    next_node_id   varchar(64) default NULL::character varying,
    settings_json  jsonb,
    condition_json jsonb,
    created_by     bigint,
    updated_by     bigint,
    deleted        smallint    default 0                 not null,
    create_time    timestamp   default CURRENT_TIMESTAMP not null,
    update_time    timestamp   default CURRENT_TIMESTAMP not null,
    constraint uk_t_ingestion_pipeline_node
        unique (pipeline_id, node_id, deleted)
);

comment on table t_ingestion_pipeline_node is '摄取流水线节点表';

comment on column t_ingestion_pipeline_node.id is '主键ID';

comment on column t_ingestion_pipeline_node.pipeline_id is '所属流水线ID';

comment on column t_ingestion_pipeline_node.node_id is '节点标识，同一流水线内唯一';

comment on column t_ingestion_pipeline_node.node_type is '节点类型';

comment on column t_ingestion_pipeline_node.next_node_id is '下一个节点标识';

comment on column t_ingestion_pipeline_node.settings_json is '节点配置JSON';

comment on column t_ingestion_pipeline_node.condition_json is '节点条件JSON';

comment on column t_ingestion_pipeline_node.created_by is '创建人用户ID';

comment on column t_ingestion_pipeline_node.updated_by is '更新人用户ID';

comment on column t_ingestion_pipeline_node.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_ingestion_pipeline_node.create_time is '创建时间';

comment on column t_ingestion_pipeline_node.update_time is '更新时间';

alter table t_ingestion_pipeline_node
    owner to postgres;

create index idx_t_ingestion_pipeline_node_pipeline
    on t_ingestion_pipeline_node (pipeline_id);


create table t_knowledge_base
(
    id              bigint generated by default as identity
        primary key,
    name            varchar(128)                                      not null,
    description     varchar(512) default NULL::character varying,
    embedding_model varchar(128)                                      not null,
    collection_name varchar(128)                                      not null,
    visibility      varchar(16)  default 'PRIVATE'::character varying not null,
    status          varchar(16)  default 'ACTIVE'::character varying  not null,
    owner_user_id   bigint,
    created_by      bigint,
    updated_by      bigint,
    deleted         smallint     default 0                            not null,
    create_time     timestamp    default CURRENT_TIMESTAMP            not null,
    update_time     timestamp    default CURRENT_TIMESTAMP            not null,
    dimension       integer,
    metric_type     varchar(32),
    allowed_roles   varchar(256) default NULL::character varying,
    constraint uk_t_knowledge_base_collection_deleted
        unique (collection_name, deleted)
);

comment on table t_knowledge_base is '知识库表';

comment on column t_knowledge_base.id is '主键ID';

comment on column t_knowledge_base.name is '知识库名称';

comment on column t_knowledge_base.description is '知识库描述';

comment on column t_knowledge_base.embedding_model is '向量化模型标识';

comment on column t_knowledge_base.collection_name is '向量集合名称';

comment on column t_knowledge_base.visibility is '可见性：PRIVATE/TEAM/PUBLIC';

comment on column t_knowledge_base.status is '状态：ACTIVE/DISABLED';

comment on column t_knowledge_base.owner_user_id is '知识库归属用户ID';

comment on column t_knowledge_base.created_by is '创建人用户ID';

comment on column t_knowledge_base.updated_by is '更新人用户ID';

comment on column t_knowledge_base.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_knowledge_base.create_time is '创建时间';

comment on column t_knowledge_base.update_time is '更新时间';

alter table t_knowledge_base
    owner to postgres;

create index idx_t_knowledge_base_name_deleted
    on t_knowledge_base (name, deleted);

create index idx_t_knowledge_base_owner_deleted
    on t_knowledge_base (owner_user_id, deleted);

create index idx_t_knowledge_base_visibility_deleted
    on t_knowledge_base (visibility, deleted);

create index idx_t_knowledge_base_status_deleted
    on t_knowledge_base (status, deleted);


create table t_knowledge_document
(
    id               bigint generated by default as identity
        primary key,
    kb_id            bigint                                             not null,
    doc_name         varchar(256)                                       not null,
    enabled          smallint      default 1                            not null,
    chunk_count      integer       default 0                            not null,
    file_url         varchar(1024) default NULL::character varying,
    file_type        varchar(32)   default NULL::character varying,
    file_size        bigint,
    process_mode     varchar(32)   default 'chunk'::character varying   not null,
    status           varchar(32)   default 'pending'::character varying not null,
    source_type      varchar(32)   default NULL::character varying,
    source_location  varchar(1024) default NULL::character varying,
    content_hash     varchar(128)  default NULL::character varying,
    schedule_enabled smallint      default 0                            not null,
    schedule_cron    varchar(128)  default NULL::character varying,
    chunk_strategy   varchar(32)   default NULL::character varying,
    chunk_config     jsonb,
    pipeline_id      bigint,
    created_by       bigint,
    updated_by       bigint,
    deleted          smallint      default 0                            not null,
    create_time      timestamp     default CURRENT_TIMESTAMP            not null,
    update_time      timestamp     default CURRENT_TIMESTAMP            not null,
    source_file_name varchar(255),
    error_message    text,
    metadata_json    jsonb
);

comment on table t_knowledge_document is '知识库文档表';

comment on column t_knowledge_document.id is '主键ID';

comment on column t_knowledge_document.kb_id is '所属知识库ID';

comment on column t_knowledge_document.doc_name is '文档名称';

comment on column t_knowledge_document.enabled is '启用标记：1启用，0禁用';

comment on column t_knowledge_document.chunk_count is '分块数量';

comment on column t_knowledge_document.file_url is '文档存储地址';

comment on column t_knowledge_document.file_type is '文档类型或MIME类型';

comment on column t_knowledge_document.file_size is '文件大小，单位字节';

comment on column t_knowledge_document.process_mode is '处理模式：chunk/pipeline';

comment on column t_knowledge_document.status is '处理状态：pending/running/success/failed';

comment on column t_knowledge_document.source_type is '来源类型：file/url/text/api';

comment on column t_knowledge_document.source_location is '来源位置或原始地址';

comment on column t_knowledge_document.content_hash is '文档内容哈希';

comment on column t_knowledge_document.schedule_enabled is '是否启用定时刷新：1启用，0禁用';

comment on column t_knowledge_document.schedule_cron is '定时刷新Cron表达式';

comment on column t_knowledge_document.chunk_strategy is '分块策略';

comment on column t_knowledge_document.chunk_config is '分块配置JSON';

comment on column t_knowledge_document.pipeline_id is '关联摄取流水线ID';

comment on column t_knowledge_document.created_by is '创建人用户ID';

comment on column t_knowledge_document.updated_by is '更新人用户ID';

comment on column t_knowledge_document.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_knowledge_document.create_time is '创建时间';

comment on column t_knowledge_document.update_time is '更新时间';

alter table t_knowledge_document
    owner to postgres;

create index idx_t_doc_kb_deleted
    on t_knowledge_document (kb_id, deleted);

create index idx_t_doc_status_deleted
    on t_knowledge_document (status, deleted);

create index idx_t_doc_created_by
    on t_knowledge_document (created_by);

create index idx_t_doc_content_hash
    on t_knowledge_document (content_hash);


create table t_knowledge_chunk
(
    id           bigint generated by default as identity
        primary key,
    kb_id        bigint                                 not null,
    doc_id       bigint                                 not null,
    chunk_index  integer                                not null,
    content      text                                   not null,
    content_hash varchar(128) default NULL::character varying,
    char_count   integer,
    token_count  integer,
    enabled      smallint     default 1                 not null,
    metadata     jsonb,
    created_by   bigint,
    updated_by   bigint,
    deleted      smallint     default 0                 not null,
    create_time  timestamp    default CURRENT_TIMESTAMP not null,
    update_time  timestamp    default CURRENT_TIMESTAMP not null,
    constraint uk_t_chunk_doc_index_deleted
        unique (doc_id, chunk_index, deleted)
);

comment on table t_knowledge_chunk is '知识库文档分块表';

comment on column t_knowledge_chunk.id is '主键ID';

comment on column t_knowledge_chunk.kb_id is '所属知识库ID';

comment on column t_knowledge_chunk.doc_id is '所属文档ID';

comment on column t_knowledge_chunk.chunk_index is '分块序号';

comment on column t_knowledge_chunk.content is '分块内容';

comment on column t_knowledge_chunk.content_hash is '分块内容哈希';

comment on column t_knowledge_chunk.char_count is '字符数';

comment on column t_knowledge_chunk.token_count is 'Token数量估算值';

comment on column t_knowledge_chunk.enabled is '启用标记：1启用，0禁用';

comment on column t_knowledge_chunk.metadata is '分块元数据JSON';

comment on column t_knowledge_chunk.created_by is '创建人用户ID';

comment on column t_knowledge_chunk.updated_by is '更新人用户ID';

comment on column t_knowledge_chunk.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_knowledge_chunk.create_time is '创建时间';

comment on column t_knowledge_chunk.update_time is '更新时间';

alter table t_knowledge_chunk
    owner to postgres;

create index idx_t_chunk_kb_deleted
    on t_knowledge_chunk (kb_id, deleted);

create index idx_t_chunk_doc_deleted
    on t_knowledge_chunk (doc_id, deleted);

create index idx_t_chunk_hash
    on t_knowledge_chunk (content_hash);


create table t_knowledge_vector
(
    id              bigint generated by default as identity
        primary key,
    kb_id           bigint                              not null,
    doc_id          bigint                              not null,
    chunk_id        bigint                              not null,
    collection_name varchar(128)                        not null,
    vector_id       varchar(128)                        not null,
    embedding_model varchar(128)                        not null,
    embedding_dim   integer,
    metadata        jsonb,
    content         text                                not null,
    embedding       vector(1536)                        not null,
    created_by      bigint,
    deleted         smallint  default 0                 not null,
    create_time     timestamp default CURRENT_TIMESTAMP not null,
    update_time     timestamp default CURRENT_TIMESTAMP not null,
    constraint uk_t_knowledge_vector_chunk_deleted
        unique (chunk_id, deleted),
    constraint uk_t_knowledge_vector_vector_deleted
        unique (collection_name, vector_id, deleted)
);

comment on table t_knowledge_vector is '知识库向量存储表';

comment on column t_knowledge_vector.id is '主键ID';

comment on column t_knowledge_vector.kb_id is '所属知识库ID';

comment on column t_knowledge_vector.doc_id is '所属文档ID';

comment on column t_knowledge_vector.chunk_id is '所属分块ID';

comment on column t_knowledge_vector.collection_name is '向量集合名称';

comment on column t_knowledge_vector.vector_id is '向量业务ID';

comment on column t_knowledge_vector.embedding_model is '向量化模型标识';

comment on column t_knowledge_vector.embedding_dim is '向量维度';

comment on column t_knowledge_vector.metadata is '向量元数据JSON';

comment on column t_knowledge_vector.content is '向量对应文本内容';

comment on column t_knowledge_vector.embedding is 'pgvector向量数据';

comment on column t_knowledge_vector.created_by is '创建人用户ID';

comment on column t_knowledge_vector.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_knowledge_vector.create_time is '创建时间';

comment on column t_knowledge_vector.update_time is '更新时间';

alter table t_knowledge_vector
    owner to postgres;

create index idx_t_knowledge_vector_kb_deleted
    on t_knowledge_vector (kb_id, deleted);

create index idx_t_knowledge_vector_doc_deleted
    on t_knowledge_vector (doc_id, deleted);

create index idx_t_knowledge_vector_collection_deleted
    on t_knowledge_vector (collection_name, deleted);

create index idx_t_knowledge_vector_metadata
    on t_knowledge_vector using gin (metadata);

create index idx_t_knowledge_vector_embedding_hnsw
    on t_knowledge_vector using hnsw (embedding vector_cosine_ops);


create table t_knowledge_document_chunk_log
(
    id               bigint generated by default as identity
        primary key,
    doc_id           bigint                                not null,
    status           varchar(20)                           not null,
    process_mode     varchar(20) default NULL::character varying,
    chunk_strategy   varchar(50) default NULL::character varying,
    pipeline_id      bigint,
    extract_duration bigint,
    chunk_duration   bigint,
    embed_duration   bigint,
    persist_duration bigint,
    total_duration   bigint,
    chunk_count      integer,
    error_message    text,
    start_time       timestamp,
    end_time         timestamp,
    create_time      timestamp   default CURRENT_TIMESTAMP not null,
    update_time      timestamp   default CURRENT_TIMESTAMP not null
);

comment on table t_knowledge_document_chunk_log is '文档切分日志表';

comment on column t_knowledge_document_chunk_log.id is '主键ID';

comment on column t_knowledge_document_chunk_log.doc_id is '所属文档ID';

comment on column t_knowledge_document_chunk_log.status is '执行状态';

comment on column t_knowledge_document_chunk_log.process_mode is '处理模式';

comment on column t_knowledge_document_chunk_log.chunk_strategy is '分块策略';

comment on column t_knowledge_document_chunk_log.pipeline_id is '关联流水线ID';

comment on column t_knowledge_document_chunk_log.extract_duration is '内容提取耗时，单位毫秒';

comment on column t_knowledge_document_chunk_log.chunk_duration is '分块耗时，单位毫秒';

comment on column t_knowledge_document_chunk_log.embed_duration is '向量化耗时，单位毫秒';

comment on column t_knowledge_document_chunk_log.persist_duration is '持久化耗时，单位毫秒';

comment on column t_knowledge_document_chunk_log.total_duration is '总耗时，单位毫秒';

comment on column t_knowledge_document_chunk_log.chunk_count is '生成分块数量';

comment on column t_knowledge_document_chunk_log.error_message is '错误信息';

comment on column t_knowledge_document_chunk_log.start_time is '开始时间';

comment on column t_knowledge_document_chunk_log.end_time is '结束时间';

comment on column t_knowledge_document_chunk_log.create_time is '创建时间';

comment on column t_knowledge_document_chunk_log.update_time is '更新时间';

alter table t_knowledge_document_chunk_log
    owner to postgres;

create index idx_t_doc_chunk_log_doc
    on t_knowledge_document_chunk_log (doc_id);

create index idx_t_doc_chunk_log_status
    on t_knowledge_document_chunk_log (status);

create index idx_t_doc_chunk_log_started
    on t_knowledge_document_chunk_log (start_time);


create table t_knowledge_document_schedule
(
    id                bigint generated by default as identity
        primary key,
    doc_id            bigint                                 not null
        constraint uk_t_doc_schedule_doc
            unique,
    kb_id             bigint                                 not null,
    cron_expr         varchar(128) default NULL::character varying,
    enabled           smallint     default 0                 not null,
    next_run_time     timestamp,
    last_run_time     timestamp,
    last_success_time timestamp,
    last_status       varchar(32)  default NULL::character varying,
    last_error        varchar(512) default NULL::character varying,
    last_etag         varchar(256) default NULL::character varying,
    last_modified     varchar(256) default NULL::character varying,
    last_content_hash varchar(128) default NULL::character varying,
    lock_owner        varchar(128) default NULL::character varying,
    lock_until        timestamp,
    create_time       timestamp    default CURRENT_TIMESTAMP not null,
    update_time       timestamp    default CURRENT_TIMESTAMP not null
);

comment on table t_knowledge_document_schedule is '文档定时刷新任务表';

comment on column t_knowledge_document_schedule.id is '主键ID';

comment on column t_knowledge_document_schedule.doc_id is '所属文档ID';

comment on column t_knowledge_document_schedule.kb_id is '所属知识库ID';

comment on column t_knowledge_document_schedule.cron_expr is 'Cron表达式';

comment on column t_knowledge_document_schedule.enabled is '启用标记：1启用，0禁用';

comment on column t_knowledge_document_schedule.next_run_time is '下次执行时间';

comment on column t_knowledge_document_schedule.last_run_time is '上次执行时间';

comment on column t_knowledge_document_schedule.last_success_time is '上次成功时间';

comment on column t_knowledge_document_schedule.last_status is '上次执行状态';

comment on column t_knowledge_document_schedule.last_error is '上次错误信息';

comment on column t_knowledge_document_schedule.last_etag is '上次ETag';

comment on column t_knowledge_document_schedule.last_modified is '上次Last-Modified值';

comment on column t_knowledge_document_schedule.last_content_hash is '上次内容哈希';

comment on column t_knowledge_document_schedule.lock_owner is '调度锁持有者';

comment on column t_knowledge_document_schedule.lock_until is '锁过期时间';

comment on column t_knowledge_document_schedule.create_time is '创建时间';

comment on column t_knowledge_document_schedule.update_time is '更新时间';

alter table t_knowledge_document_schedule
    owner to postgres;

create index idx_t_doc_schedule_kb
    on t_knowledge_document_schedule (kb_id);

create index idx_t_doc_schedule_next_run
    on t_knowledge_document_schedule (next_run_time);

create index idx_t_doc_schedule_lock_until
    on t_knowledge_document_schedule (lock_until);


create table t_knowledge_document_schedule_exec
(
    id            bigint generated by default as identity
        primary key,
    schedule_id   bigint                                 not null,
    doc_id        bigint                                 not null,
    kb_id         bigint                                 not null,
    status        varchar(32)                            not null,
    message       varchar(512) default NULL::character varying,
    start_time    timestamp,
    end_time      timestamp,
    file_name     varchar(512) default NULL::character varying,
    file_size     bigint,
    content_hash  varchar(128) default NULL::character varying,
    etag          varchar(256) default NULL::character varying,
    last_modified varchar(256) default NULL::character varying,
    create_time   timestamp    default CURRENT_TIMESTAMP not null,
    update_time   timestamp    default CURRENT_TIMESTAMP not null
);

comment on table t_knowledge_document_schedule_exec is '文档定时刷新执行记录表';

comment on column t_knowledge_document_schedule_exec.id is '主键ID';

comment on column t_knowledge_document_schedule_exec.schedule_id is '所属调度任务ID';

comment on column t_knowledge_document_schedule_exec.doc_id is '所属文档ID';

comment on column t_knowledge_document_schedule_exec.kb_id is '所属知识库ID';

comment on column t_knowledge_document_schedule_exec.status is '执行状态';

comment on column t_knowledge_document_schedule_exec.message is '执行消息';

comment on column t_knowledge_document_schedule_exec.start_time is '开始时间';

comment on column t_knowledge_document_schedule_exec.end_time is '结束时间';

comment on column t_knowledge_document_schedule_exec.file_name is '拉取到的文件名';

comment on column t_knowledge_document_schedule_exec.file_size is '拉取到的文件大小';

comment on column t_knowledge_document_schedule_exec.content_hash is '内容哈希';

comment on column t_knowledge_document_schedule_exec.etag is 'ETag值';

comment on column t_knowledge_document_schedule_exec.last_modified is 'Last-Modified值';

comment on column t_knowledge_document_schedule_exec.create_time is '创建时间';

comment on column t_knowledge_document_schedule_exec.update_time is '更新时间';

alter table t_knowledge_document_schedule_exec
    owner to postgres;

create index idx_t_doc_schedule_exec_schedule_time
    on t_knowledge_document_schedule_exec (schedule_id, start_time);

create index idx_t_doc_schedule_exec_doc
    on t_knowledge_document_schedule_exec (doc_id);

create index idx_t_doc_schedule_exec_kb
    on t_knowledge_document_schedule_exec (kb_id);


create table t_ingestion_task
(
    id               bigint generated by default as identity
        primary key,
    pipeline_id      bigint,
    kb_id            bigint,
    doc_id           bigint,
    source_type      varchar(20)                            not null,
    source_location  text,
    source_file_name varchar(255) default NULL::character varying,
    status           varchar(20)                            not null,
    chunk_count      integer      default 0                 not null,
    error_message    text,
    logs_json        jsonb,
    metadata_json    jsonb,
    started_at       timestamp,
    completed_at     timestamp,
    created_by       bigint,
    updated_by       bigint,
    deleted          smallint     default 0                 not null,
    create_time      timestamp    default CURRENT_TIMESTAMP not null,
    update_time      timestamp    default CURRENT_TIMESTAMP not null
);

comment on table t_ingestion_task is '摄取任务表';

comment on column t_ingestion_task.id is '主键ID';

comment on column t_ingestion_task.pipeline_id is '关联流水线ID';

comment on column t_ingestion_task.kb_id is '关联知识库ID';

comment on column t_ingestion_task.doc_id is '关联文档ID';

comment on column t_ingestion_task.source_type is '来源类型';

comment on column t_ingestion_task.source_location is '来源地址或原始内容位置';

comment on column t_ingestion_task.source_file_name is '原始文件名';

comment on column t_ingestion_task.status is '任务状态';

comment on column t_ingestion_task.chunk_count is '生成分块数量';

comment on column t_ingestion_task.error_message is '错误信息';

comment on column t_ingestion_task.logs_json is '节点日志JSON';

comment on column t_ingestion_task.metadata_json is '扩展元数据JSON';

comment on column t_ingestion_task.started_at is '开始时间';

comment on column t_ingestion_task.completed_at is '完成时间';

comment on column t_ingestion_task.created_by is '创建人用户ID';

comment on column t_ingestion_task.updated_by is '更新人用户ID';

comment on column t_ingestion_task.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_ingestion_task.create_time is '创建时间';

comment on column t_ingestion_task.update_time is '更新时间';

alter table t_ingestion_task
    owner to postgres;

create index idx_t_ingestion_task_pipeline
    on t_ingestion_task (pipeline_id);

create index idx_t_ingestion_task_kb_doc
    on t_ingestion_task (kb_id, doc_id);

create index idx_t_ingestion_task_status
    on t_ingestion_task (status);

create index idx_t_ingestion_task_created_by
    on t_ingestion_task (created_by);


create table t_ingestion_task_node
(
    id            bigint generated by default as identity
        primary key,
    task_id       bigint                              not null,
    pipeline_id   bigint,
    node_id       varchar(64)                         not null,
    node_type     varchar(30)                         not null,
    node_order    integer   default 0                 not null,
    status        varchar(20)                         not null,
    duration_ms   bigint    default 0                 not null,
    message       text,
    error_message text,
    output_json   text,
    deleted       smallint  default 0                 not null,
    create_time   timestamp default CURRENT_TIMESTAMP not null,
    update_time   timestamp default CURRENT_TIMESTAMP not null
);

comment on table t_ingestion_task_node is '摄取任务节点表';

comment on column t_ingestion_task_node.id is '主键ID';

comment on column t_ingestion_task_node.task_id is '所属任务ID';

comment on column t_ingestion_task_node.pipeline_id is '所属流水线ID';

comment on column t_ingestion_task_node.node_id is '节点标识';

comment on column t_ingestion_task_node.node_type is '节点类型';

comment on column t_ingestion_task_node.node_order is '节点执行顺序';

comment on column t_ingestion_task_node.status is '节点状态';

comment on column t_ingestion_task_node.duration_ms is '节点执行耗时，单位毫秒';

comment on column t_ingestion_task_node.message is '节点执行消息';

comment on column t_ingestion_task_node.error_message is '节点错误信息';

comment on column t_ingestion_task_node.output_json is '节点输出JSON';

comment on column t_ingestion_task_node.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_ingestion_task_node.create_time is '创建时间';

comment on column t_ingestion_task_node.update_time is '更新时间';

alter table t_ingestion_task_node
    owner to postgres;

create index idx_t_ingestion_task_node_task
    on t_ingestion_task_node (task_id);

create index idx_t_ingestion_task_node_pipeline
    on t_ingestion_task_node (pipeline_id);

create index idx_t_ingestion_task_node_status
    on t_ingestion_task_node (status);


create table t_conversation
(
    id              bigint generated by default as identity
        primary key,
    conversation_id varchar(64)                         not null,
    user_id         bigint                              not null,
    title           varchar(128)                        not null,
    last_time       timestamp,
    deleted         smallint  default 0                 not null,
    create_time     timestamp default CURRENT_TIMESTAMP not null,
    update_time     timestamp default CURRENT_TIMESTAMP not null,
    constraint uk_t_conversation_user
        unique (conversation_id, user_id)
);

comment on table t_conversation is '会话列表';

comment on column t_conversation.id is '主键ID';

comment on column t_conversation.conversation_id is '业务会话ID';

comment on column t_conversation.user_id is '所属用户ID';

comment on column t_conversation.title is '会话标题';

comment on column t_conversation.last_time is '最近消息时间';

comment on column t_conversation.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_conversation.create_time is '创建时间';

comment on column t_conversation.update_time is '更新时间';

alter table t_conversation
    owner to postgres;

create index idx_t_conversation_user_time
    on t_conversation (user_id, last_time);

create index idx_t_conversation_deleted
    on t_conversation (deleted);


create table t_conversation_summary
(
    id              bigint generated by default as identity
        primary key,
    conversation_id varchar(64)                         not null,
    user_id         bigint                              not null,
    last_message_id bigint                              not null,
    content         text                                not null,
    deleted         smallint  default 0                 not null,
    create_time     timestamp default CURRENT_TIMESTAMP not null,
    update_time     timestamp default CURRENT_TIMESTAMP not null
);

comment on table t_conversation_summary is '会话摘要表';

comment on column t_conversation_summary.id is '主键ID';

comment on column t_conversation_summary.conversation_id is '业务会话ID';

comment on column t_conversation_summary.user_id is '所属用户ID';

comment on column t_conversation_summary.last_message_id is '摘要对应的最后一条消息ID';

comment on column t_conversation_summary.content is '摘要内容';

comment on column t_conversation_summary.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_conversation_summary.create_time is '创建时间';

comment on column t_conversation_summary.update_time is '更新时间';

alter table t_conversation_summary
    owner to postgres;

create index idx_t_conversation_summary_conv_user
    on t_conversation_summary (conversation_id, user_id);


create table t_message
(
    id                bigint generated by default as identity
        primary key,
    conversation_id   varchar(64)                         not null,
    user_id           bigint                              not null,
    role              varchar(32)                         not null,
    content           text                                not null,
    thinking_content  text,
    thinking_duration integer,
    metadata          jsonb,
    deleted           smallint  default 0                 not null,
    create_time       timestamp default CURRENT_TIMESTAMP not null,
    update_time       timestamp default CURRENT_TIMESTAMP not null
);

comment on table t_message is '会话消息记录表';

comment on column t_message.id is '主键ID';

comment on column t_message.conversation_id is '业务会话ID';

comment on column t_message.user_id is '所属用户ID';

comment on column t_message.role is '消息角色：system/user/assistant/tool';

comment on column t_message.content is '消息内容';

comment on column t_message.thinking_content is '深度思考内容';

comment on column t_message.thinking_duration is '深度思考耗时，单位秒';

comment on column t_message.metadata is '消息元数据JSON';

comment on column t_message.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_message.create_time is '创建时间';

comment on column t_message.update_time is '更新时间';

alter table t_message
    owner to postgres;

create index idx_t_message_conv_user_time
    on t_message (conversation_id, user_id, create_time);

create index idx_t_message_user_time
    on t_message (user_id, create_time);


create table t_message_feedback
(
    id              bigint generated by default as identity
        primary key,
    message_id      bigint                                  not null,
    conversation_id varchar(64)                             not null,
    user_id         bigint                                  not null,
    vote            smallint                                not null,
    reason          varchar(255)  default NULL::character varying,
    comment         varchar(1024) default NULL::character varying,
    deleted         smallint      default 0                 not null,
    create_time     timestamp     default CURRENT_TIMESTAMP not null,
    update_time     timestamp     default CURRENT_TIMESTAMP not null,
    constraint uk_t_message_feedback_msg_user
        unique (message_id, user_id)
);

comment on table t_message_feedback is '会话消息反馈表';

comment on column t_message_feedback.id is '主键ID';

comment on column t_message_feedback.message_id is '关联消息ID';

comment on column t_message_feedback.conversation_id is '业务会话ID';

comment on column t_message_feedback.user_id is '所属用户ID';

comment on column t_message_feedback.vote is '反馈投票：1点赞，-1点踩';

comment on column t_message_feedback.reason is '反馈原因';

comment on column t_message_feedback.comment is '反馈补充说明';

comment on column t_message_feedback.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_message_feedback.create_time is '创建时间';

comment on column t_message_feedback.update_time is '更新时间';

alter table t_message_feedback
    owner to postgres;

create index idx_t_message_feedback_conversation
    on t_message_feedback (conversation_id);

create index idx_t_message_feedback_user
    on t_message_feedback (user_id);


create table t_sample_question
(
    id          bigint generated by default as identity
        primary key,
    kb_id       bigint,
    title       varchar(64)  default NULL::character varying,
    description varchar(255) default NULL::character varying,
    question    varchar(1024)                          not null,
    sort_order  integer      default 0                 not null,
    enabled     smallint     default 1                 not null,
    deleted     smallint     default 0                 not null,
    create_time timestamp    default CURRENT_TIMESTAMP not null,
    update_time timestamp    default CURRENT_TIMESTAMP not null
);

comment on table t_sample_question is '示例问题表';

comment on column t_sample_question.id is '主键ID';

comment on column t_sample_question.kb_id is '关联知识库ID';

comment on column t_sample_question.title is '展示标题';

comment on column t_sample_question.description is '描述或提示信息';

comment on column t_sample_question.question is '示例问题内容';

comment on column t_sample_question.sort_order is '排序值';

comment on column t_sample_question.enabled is '启用标记：1启用，0禁用';

comment on column t_sample_question.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_sample_question.create_time is '创建时间';

comment on column t_sample_question.update_time is '更新时间';

alter table t_sample_question
    owner to postgres;

create index idx_t_sample_question_kb_deleted
    on t_sample_question (kb_id, deleted);

create index idx_t_sample_question_enabled
    on t_sample_question (enabled, deleted);

INSERT INTO public.t_sample_question (id, kb_id, title, description, question, sort_order, enabled, deleted, create_time, update_time) VALUES (2, 1, '今日天气查询', '查询当地今天的真实天气，走 MCP 天气工具', '广州今天的天气怎么样？', 2, 1, 0, '2026-05-30 02:26:08.297554', '2026-06-08 08:05:42.795456');
INSERT INTO public.t_sample_question (id, kb_id, title, description, question, sort_order, enabled, deleted, create_time, update_time) VALUES (1, 1, 'Java 知识文档', '适合查看 Java、Spring Boot 和项目实现细节', 'Bean的生命周期？', 1, 1, 0, '2026-05-30 02:26:08.297554', '2026-06-08 08:05:42.795456');
INSERT INTO public.t_sample_question (id, kb_id, title, description, question, sort_order, enabled, deleted, create_time, update_time) VALUES (3, 1, '聊天记录检索', '可询问聊天记录相关内容，查询前请先联系管理员开通权限', 'xxx什么时候提起过xxx?', 3, 1, 0, '2026-05-30 02:26:08.297554', '2026-06-08 08:05:42.795456');


create table t_intent_node
(
    id                    bigint generated by default as identity
        primary key,
    kb_id                 bigint,
    intent_code           varchar(64)                            not null,
    name                  varchar(64)                            not null,
    level                 smallint                               not null,
    parent_code           varchar(64)  default NULL::character varying,
    description           varchar(512) default NULL::character varying,
    examples              text,
    collection_name       varchar(128) default NULL::character varying,
    top_k                 integer,
    mcp_tool_id           varchar(128) default NULL::character varying,
    kind                  smallint     default 0                 not null,
    prompt_snippet        text,
    prompt_template       text,
    param_prompt_template text,
    sort_order            integer      default 0                 not null,
    enabled               smallint     default 1                 not null,
    created_by            bigint,
    updated_by            bigint,
    deleted               smallint     default 0                 not null,
    create_time           timestamp    default CURRENT_TIMESTAMP not null,
    update_time           timestamp    default CURRENT_TIMESTAMP not null,
    constraint uk_t_intent_code_deleted
        unique (intent_code, deleted)
);

comment on table t_intent_node is '意图树节点配置表';

comment on column t_intent_node.id is '主键ID';

comment on column t_intent_node.kb_id is '关联知识库ID';

comment on column t_intent_node.intent_code is '意图唯一编码';

comment on column t_intent_node.name is '意图名称';

comment on column t_intent_node.level is '层级：0领域，1分类，2主题';

comment on column t_intent_node.parent_code is '父级意图编码';

comment on column t_intent_node.description is '语义描述';

comment on column t_intent_node.examples is '示例问法';

comment on column t_intent_node.collection_name is '关联向量集合名称';

comment on column t_intent_node.top_k is '检索TopK';

comment on column t_intent_node.mcp_tool_id is '关联MCP工具ID';

comment on column t_intent_node.kind is '节点类型：0知识库RAG，1系统交互';

comment on column t_intent_node.prompt_snippet is '提示词片段';

comment on column t_intent_node.prompt_template is '提示词模板';

comment on column t_intent_node.param_prompt_template is '参数提取提示词模板';

comment on column t_intent_node.sort_order is '排序值';

comment on column t_intent_node.enabled is '启用标记：1启用，0禁用';

comment on column t_intent_node.created_by is '创建人用户ID';

comment on column t_intent_node.updated_by is '更新人用户ID';

comment on column t_intent_node.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_intent_node.create_time is '创建时间';

comment on column t_intent_node.update_time is '更新时间';

alter table t_intent_node
    owner to postgres;

create index idx_t_intent_kb_deleted
    on t_intent_node (kb_id, deleted);

create index idx_t_intent_parent
    on t_intent_node (parent_code);

create index idx_t_intent_enabled
    on t_intent_node (enabled, deleted);


create table t_query_term_mapping
(
    id          bigint generated by default as identity
        primary key,
    domain      varchar(64)  default NULL::character varying,
    source_term varchar(128)                           not null,
    target_term varchar(128)                           not null,
    match_type  smallint     default 1                 not null,
    priority    integer      default 100               not null,
    enabled     smallint     default 1                 not null,
    remark      varchar(255) default NULL::character varying,
    created_by  bigint,
    updated_by  bigint,
    deleted     smallint     default 0                 not null,
    create_time timestamp    default CURRENT_TIMESTAMP not null,
    update_time timestamp    default CURRENT_TIMESTAMP not null
);

comment on table t_query_term_mapping is '查询术语归一化映射表';

comment on column t_query_term_mapping.id is '主键ID';

comment on column t_query_term_mapping.domain is '业务域';

comment on column t_query_term_mapping.source_term is '原始术语';

comment on column t_query_term_mapping.target_term is '归一化术语';

comment on column t_query_term_mapping.match_type is '匹配类型';

comment on column t_query_term_mapping.priority is '优先级，值越小优先级越高';

comment on column t_query_term_mapping.enabled is '启用标记：1启用，0禁用';

comment on column t_query_term_mapping.remark is '备注';

comment on column t_query_term_mapping.created_by is '创建人用户ID';

comment on column t_query_term_mapping.updated_by is '更新人用户ID';

comment on column t_query_term_mapping.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_query_term_mapping.create_time is '创建时间';

comment on column t_query_term_mapping.update_time is '更新时间';

alter table t_query_term_mapping
    owner to postgres;

create index idx_t_term_domain
    on t_query_term_mapping (domain);

create index idx_t_term_source
    on t_query_term_mapping (source_term);

create index idx_t_term_enabled
    on t_query_term_mapping (enabled, deleted);


create table t_rag_trace_run
(
    id              bigint generated by default as identity
        primary key,
    trace_id        varchar(64)                                        not null
        constraint uk_t_rag_trace_run_trace
            unique,
    trace_name      varchar(128)  default NULL::character varying,
    entry_method    varchar(256)  default NULL::character varying,
    conversation_id varchar(64)   default NULL::character varying,
    task_id         varchar(64)   default NULL::character varying,
    user_id         bigint,
    status          varchar(16)   default 'RUNNING'::character varying not null,
    error_message   varchar(1000) default NULL::character varying,
    start_time      timestamp(3)  default NULL::timestamp without time zone,
    end_time        timestamp(3)  default NULL::timestamp without time zone,
    duration_ms     bigint,
    extra_data      jsonb,
    deleted         smallint      default 0                            not null,
    create_time     timestamp     default CURRENT_TIMESTAMP            not null,
    update_time     timestamp     default CURRENT_TIMESTAMP            not null
);

comment on table t_rag_trace_run is 'RAG Trace运行记录表';

comment on column t_rag_trace_run.id is '主键ID';

comment on column t_rag_trace_run.trace_id is '全局链路ID';

comment on column t_rag_trace_run.trace_name is '链路名称';

comment on column t_rag_trace_run.entry_method is '入口方法';

comment on column t_rag_trace_run.conversation_id is '业务会话ID';

comment on column t_rag_trace_run.task_id is '任务ID';

comment on column t_rag_trace_run.user_id is '用户ID';

comment on column t_rag_trace_run.status is '执行状态：RUNNING/SUCCESS/ERROR';

comment on column t_rag_trace_run.error_message is '错误信息';

comment on column t_rag_trace_run.start_time is '开始时间';

comment on column t_rag_trace_run.end_time is '结束时间';

comment on column t_rag_trace_run.duration_ms is '执行耗时，单位毫秒';

comment on column t_rag_trace_run.extra_data is '扩展数据JSON';

comment on column t_rag_trace_run.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_rag_trace_run.create_time is '创建时间';

comment on column t_rag_trace_run.update_time is '更新时间';

alter table t_rag_trace_run
    owner to postgres;

create index idx_t_rag_trace_run_task
    on t_rag_trace_run (task_id);

create index idx_t_rag_trace_run_user
    on t_rag_trace_run (user_id);

create index idx_t_rag_trace_run_status
    on t_rag_trace_run (status);


create table t_rag_trace_node
(
    id             bigint generated by default as identity
        primary key,
    trace_id       varchar(64)                                        not null,
    node_id        varchar(64)                                        not null,
    parent_node_id varchar(64)   default NULL::character varying,
    depth          integer       default 0                            not null,
    node_type      varchar(64)   default NULL::character varying,
    node_name      varchar(128)  default NULL::character varying,
    class_name     varchar(256)  default NULL::character varying,
    method_name    varchar(128)  default NULL::character varying,
    status         varchar(16)   default 'RUNNING'::character varying not null,
    error_message  varchar(1000) default NULL::character varying,
    start_time     timestamp(3)  default NULL::timestamp without time zone,
    end_time       timestamp(3)  default NULL::timestamp without time zone,
    duration_ms    bigint,
    extra_data     jsonb,
    deleted        smallint      default 0                            not null,
    create_time    timestamp     default CURRENT_TIMESTAMP            not null,
    update_time    timestamp     default CURRENT_TIMESTAMP            not null,
    constraint uk_t_rag_trace_node_run_node
        unique (trace_id, node_id)
);

comment on table t_rag_trace_node is 'RAG Trace节点记录表';

comment on column t_rag_trace_node.id is '主键ID';

comment on column t_rag_trace_node.trace_id is '所属链路ID';

comment on column t_rag_trace_node.node_id is '节点ID';

comment on column t_rag_trace_node.parent_node_id is '父节点ID';

comment on column t_rag_trace_node.depth is '节点深度';

comment on column t_rag_trace_node.node_type is '节点类型';

comment on column t_rag_trace_node.node_name is '节点名称';

comment on column t_rag_trace_node.class_name is '类名';

comment on column t_rag_trace_node.method_name is '方法名';

comment on column t_rag_trace_node.status is '执行状态：RUNNING/SUCCESS/ERROR';

comment on column t_rag_trace_node.error_message is '错误信息';

comment on column t_rag_trace_node.start_time is '开始时间';

comment on column t_rag_trace_node.end_time is '结束时间';

comment on column t_rag_trace_node.duration_ms is '执行耗时，单位毫秒';

comment on column t_rag_trace_node.extra_data is '扩展数据JSON';

comment on column t_rag_trace_node.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_rag_trace_node.create_time is '创建时间';

comment on column t_rag_trace_node.update_time is '更新时间';

alter table t_rag_trace_node
    owner to postgres;

create index idx_t_rag_trace_node_parent
    on t_rag_trace_node (trace_id, parent_node_id);

create index idx_t_rag_trace_node_status
    on t_rag_trace_node (status);


create table t_rag_question_quota_config
(
    id          bigint generated by default as identity
        primary key,
    config_key  varchar(64)                            not null,
    daily_limit integer      default 5                 not null,
    remark      varchar(255) default NULL::character varying,
    deleted     smallint     default 0                 not null,
    create_time timestamp    default CURRENT_TIMESTAMP not null,
    update_time timestamp    default CURRENT_TIMESTAMP not null,
    constraint uk_t_rag_question_quota_config_key_deleted
        unique (config_key, deleted)
);

comment on table t_rag_question_quota_config is 'RAG每日提问配额配置表';

comment on column t_rag_question_quota_config.id is '主键ID';

comment on column t_rag_question_quota_config.config_key is '配置键名，当前用于全局每日提问上限';

comment on column t_rag_question_quota_config.daily_limit is '每日提问上限，最小值为 1';

comment on column t_rag_question_quota_config.remark is '配置备注';

comment on column t_rag_question_quota_config.deleted is '逻辑删除标记：0正常，1删除';

comment on column t_rag_question_quota_config.create_time is '创建时间';

comment on column t_rag_question_quota_config.update_time is '更新时间';

alter table t_rag_question_quota_config
    owner to postgres;


create table t_rag_question_quota_audit
(
    id              bigint generated by default as identity
        primary key,
    action_type     varchar(32)                            not null,
    actor_user_id   bigint                                 not null,
    actor_username  varchar(64)  default NULL::character varying,
    actor_role      varchar(64)  default NULL::character varying,
    target_user_id  bigint,
    target_username varchar(64)  default NULL::character varying,
    old_daily_limit integer,
    new_daily_limit integer,
    remark          varchar(512) default NULL::character varying,
    create_time     timestamp    default CURRENT_TIMESTAMP not null,
    update_time     timestamp    default CURRENT_TIMESTAMP not null
);

comment on table t_rag_question_quota_audit is 'RAG每日提问配额操作审计表';

comment on column t_rag_question_quota_audit.id is '主键ID';

comment on column t_rag_question_quota_audit.action_type is '操作类型：UPDATE_LIMIT/RESET_USER_COUNT';

comment on column t_rag_question_quota_audit.actor_user_id is '操作人用户ID';

comment on column t_rag_question_quota_audit.actor_username is '操作人用户名';

comment on column t_rag_question_quota_audit.actor_role is '操作人角色表达式';

comment on column t_rag_question_quota_audit.target_user_id is '目标用户ID';

comment on column t_rag_question_quota_audit.target_username is '目标用户名';

comment on column t_rag_question_quota_audit.old_daily_limit is '修改前每日上限';

comment on column t_rag_question_quota_audit.new_daily_limit is '修改后每日上限';

comment on column t_rag_question_quota_audit.remark is '操作备注';

comment on column t_rag_question_quota_audit.create_time is '创建时间';

comment on column t_rag_question_quota_audit.update_time is '更新时间';

alter table t_rag_question_quota_audit
    owner to postgres;


