-- ============================================================
-- Script type: migration
-- Version: M20260608
-- Module: rag
-- Description: Persist daily question quota configuration and audit logs.
-- ============================================================

create table if not exists t_rag_question_quota_config (
    id            bigint generated by default as identity,
    config_key    varchar(64) not null,
    daily_limit   int not null default 5,
    remark        varchar(255) default null,
    deleted       smallint not null default 0,
    create_time   timestamp not null default current_timestamp,
    update_time   timestamp not null default current_timestamp,
    primary key (id),
    constraint uk_t_rag_question_quota_config_key_deleted unique (config_key, deleted)
);

create table if not exists t_rag_question_quota_audit (
    id               bigint generated by default as identity,
    action_type      varchar(32) not null,
    actor_user_id    bigint not null,
    actor_username   varchar(64) default null,
    actor_role       varchar(64) default null,
    target_user_id   bigint default null,
    target_username  varchar(64) default null,
    old_daily_limit  int default null,
    new_daily_limit  int default null,
    remark           varchar(512) default null,
    create_time      timestamp not null default current_timestamp,
    update_time      timestamp not null default current_timestamp,
    primary key (id)
);

comment on table t_rag_question_quota_config is 'RAG每日提问配额配置表';
comment on column t_rag_question_quota_config.id is '主键ID';
comment on column t_rag_question_quota_config.config_key is '配置键名，当前用于全局每日提问上限';
comment on column t_rag_question_quota_config.daily_limit is '每日提问上限，最小值为 1';
comment on column t_rag_question_quota_config.remark is '配置备注';
comment on column t_rag_question_quota_config.deleted is '逻辑删除标记：0正常，1删除';
comment on column t_rag_question_quota_config.create_time is '创建时间';
comment on column t_rag_question_quota_config.update_time is '更新时间';

comment on table t_rag_question_quota_audit is 'RAG每日提问配额操作审计表';
comment on column t_rag_question_quota_audit.id is '主键ID';
comment on column t_rag_question_quota_audit.action_type is '操作类型：UPDATE_LIMIT/RESET_USER_COUNT';
comment on column t_rag_question_quota_audit.actor_user_id is '操作人用户ID';
comment on column t_rag_question_quota_audit.actor_username is '操作人用户名';
comment on column t_rag_question_quota_audit.actor_role is '操作人角色表达式';
comment on column t_rag_question_quota_audit.target_user_id is '目标用户ID';
comment on column t_rag_question_quota_audit.target_username is '目标用户名';
comment on column t_rag_question_quota_audit.old_daily_limit is '修改前每日上限';
comment on column t_rag_question_quota_audit.new_daily_limit is '修改后每日上限';
comment on column t_rag_question_quota_audit.remark is '操作备注';
comment on column t_rag_question_quota_audit.create_time is '创建时间';
comment on column t_rag_question_quota_audit.update_time is '更新时间';

insert into t_rag_question_quota_config (
    config_key,
    daily_limit,
    remark,
    deleted,
    create_time,
    update_time
)
select 'global_daily_question_limit',
       5,
       '全局每日提问上限',
       0,
       current_timestamp,
       current_timestamp
where not exists (
    select 1
    from t_rag_question_quota_config
    where config_key = 'global_daily_question_limit'
      and deleted = 0
);
