package com.personalblog.ragbackend.knowledge.service.vector;

import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * PG向量存储管理端类
 */
@Component
@ConditionalOnProperty(name = "rag.vector.type", havingValue = "pg")
public class PgVectorStoreAdmin implements VectorStoreAdmin {
    private final JdbcTemplate jdbcTemplate;
    private static final String SCHEMA = "public";
    private static final String TABLE_NAME = "t_knowledge_vector";

    public PgVectorStoreAdmin(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void ensureVectorSpace(KnowledgeVectorSpace vectorSpace) {
        String schema = identifier(SCHEMA);
        String table = identifier(TABLE_NAME);
        String qualifiedTable = schema + "." + table;
        jdbcTemplate.execute("create schema if not exists " + schema);
        jdbcTemplate.execute("create extension if not exists vector");
        jdbcTemplate.execute("""
                create table if not exists %s (
                    id bigint generated by default as identity primary key,
                    kb_id bigint,
                    doc_id bigint,
                    chunk_id bigint,
                    collection_name varchar(128) not null,
                    vector_id varchar(128) not null,
                    embedding_model varchar(128) not null,
                    embedding_dim integer,
                    content text not null,
                    metadata jsonb,
                    embedding vector(%d) not null,
                    created_by bigint,
                    deleted smallint not null default 0,
                    create_time timestamp not null default current_timestamp,
                    update_time timestamp not null default current_timestamp
                )
                """.formatted(qualifiedTable, vectorSpace.dimension()));
        jdbcTemplate.execute("""
                create unique index if not exists uk_t_knowledge_vector_chunk_deleted
                on %s (chunk_id, deleted)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create unique index if not exists uk_t_knowledge_vector_vector_deleted
                on %s (collection_name, vector_id, deleted)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create index if not exists idx_t_knowledge_vector_collection_deleted
                on %s (collection_name, deleted)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create index if not exists idx_t_knowledge_vector_metadata
                on %s using gin (metadata)
                """.formatted(qualifiedTable));
        jdbcTemplate.execute("""
                create index if not exists idx_t_knowledge_vector_embedding_hnsw
                on %s using hnsw (embedding vector_cosine_ops)
                """.formatted(qualifiedTable));
    }

    @Override
    public boolean vectorSpaceExists(KnowledgeVectorSpaceId spaceId) {
        String schema = SCHEMA;
        String tableName = TABLE_NAME;
        Integer count = jdbcTemplate.queryForObject("""
                select count(*)
                from information_schema.tables
                where table_schema = ? and table_name = ?
                """, Integer.class, schema, tableName);
        return count != null && count > 0;
    }

    private String identifier(String value) {
        if (value == null || !value.matches("[A-Za-z_][A-Za-z0-9_]*")) {
            throw new IllegalArgumentException("Invalid PostgreSQL identifier: " + value);
        }
        return value;
    }
}
